build:
    environment:
        go: 'go1.12'
    nodes:
        tests-with-coverage:
            tests:
                override:
                    -
                        command: go test -coverprofile=cover.out
                        coverage:
                            file: 'cover.out'
                            format: 'go-cc'
